services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: ${GITLAB_DOMAIN}
    shm_size: '256m'

    ports:
      - "127.0.0.1:${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"

    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'

        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        gitlab_rails['trusted_proxies'] = ['${TRUSTED_PROXIES}']
        gitlab_rails['time_zone'] = '${GITLAB_TIMEZONE}'

        puma['worker_processes'] = ${GITLAB_PUMA_WORKERS}
        sidekiq['max_concurrency'] = ${GITLAB_SIDEKIQ_CONCURRENCY}
